apiVersion: v1
kind: Service
metada:
  name: nginx
  labels:
    app: nginx 
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer